src/excuses/urls.py
from django.conf.urls import url

from excuses import views

app_name = "excuses"

urlpatterns = [
    url(r'^all/$', views.excuse_list, name='excuse_list'),
    url(r'^create/$', views.excuse_create, name='excuse_create'),
    url(r'^(?P<id>\d+)/edit/$', views.excuse_edit, name='excuse_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.ExcuseDelete.as_view(), name='excuse_delete'),

]

src/flex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from events import views as event_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

app_name = "flex"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', event_views.event_list, name='home'),
    # installed apps
    # url(r'^summernote/', include('django_summernote.urls')),
    # url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^select2/', include('django_select2.urls')),
    # custom apps
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^excuses/', include(('excuses.urls', 'excuses'), namespace='excuses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url

from . import views

app_name = "profiles"

urlpatterns = [
    # url(r'^$', views.ProfileList.as_view(), name='list'),
    # url(r'^import/$', views.mass_user_import, name='import'),
    url(r'^update/mass/$', views.mass_update, name='mass_update'),
    url(r'^(?P<id>\d+)/reset/$', views.reset_password_to_default, name='reset_password'),
    url(r'^permissions/update/$', views.permissions_update, name='permissions_update'),

]

src/profiles/models.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

from django.db.models.signals import post_save
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse

from excuses.models import Excuse


class PasswordResetRequiredMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        # One-time configuration and initialization.

    def __call__(self, request):
        # Code to be executed for each request before
        # the view (and later middleware) are called.

        response = self.get_response(request)

        # Code to be executed for each request/response after
        # the view is called.
        try:
            if request.user.is_authenticated:
                if request.path == reverse('auth_password_change_done'):
                    request.user.profile.password_change_required = False
                    request.user.profile.save()
                    messages.success(request, "Password successfully changed.")
                    response = redirect('home')
                elif request.user.profile.password_change_required:
                    if request.path != reverse('auth_password_change') and \
                       request.path != reverse('auth_logout'):
                        response = HttpResponseRedirect(reverse('auth_password_change'))
        except Profile.DoesNotExist:
            messages.error(request, "You don't seem to have a profile?")

        return response


class ProfileManager(models.Manager):
    def all_active_students(self):
        qs = self.get_queryset().select_related('user')
        return qs.filter(user__is_active=True, user__is_staff=False)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    homeroom_teacher = models.ForeignKey(settings.AUTH_USER_MODEL,
                                         on_delete=models.SET_NULL,
                                         limit_choices_to={'is_staff': True},
                                         related_name='students',
                                         null=True, blank=True
                                         )
    grade = models.IntegerField(null=True, blank=True)
    phone = models.CharField(max_length=13, null=True, blank=True, help_text="Format: (000)000-0000")
    email = models.EmailField(null=True, blank=True)
    permission = models.NullBooleanField(null=True)
    password_change_required = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)  # Used to determine if student is still active after an import.

    objects = ProfileManager()

    def __str__(self):
        return str(self.user.username) + " (" + str(self.user.first_name) + " " + str(self.user.last_name) + ")"


def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        Profile.objects.create(user=user)


post_save.connect(create_profile, sender=User)

src/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django_select2.forms import ModelSelect2MultipleWidget

from profiles.models import Profile


class UserImportForm(forms.Form):
    SEMESTERS = (
        ('SEM1', 'SEM1'),
        ('SEM2', 'SEM2'),
    )
    semester = forms.ChoiceField(choices=SEMESTERS, initial='SEM1',
                                 help_text='This will ensure the proper homeroom teacher when updating students')

    student_csv_file = forms.FileField(label="Student Data File",
                                       required=False,
                                       help_text="A csv file with at least these headings: Usual first name, Usual surname, Grade, StudentEmail, Teacher ID, StudentHomePhoneNumber, EmergencyContact1Email1"
    )
    staff_csv_file = forms.FileField(label="Staff Data File",
                                     required=False,
                                     help_text="A csv file with these headings: id, first_name, last_name, position, email")


class StudentsCustomTitleWidget(ModelSelect2MultipleWidget):
    model = Profile
    queryset = Profile.objects.all_active_students()

    search_fields = [
        'user__first_name__istartswith',
        'user__last_name__istartswith',
        'user__username__istartswith',
    ]

    def label_from_instance(self, obj):
        return obj.user.get_full_name().upper()


class PermissionForm(forms.Form):

    students_permission_granted = forms.ModelMultipleChoiceField(
        queryset=Profile.objects.all_active_students(),
        widget=StudentsCustomTitleWidget,
        help_text="List students with permission to attend low risk excursions during flex.",
        required=False,
    )
    students_permission_rejected = forms.ModelMultipleChoiceField(
        queryset=Profile.objects.all_active_students(),
        widget=StudentsCustomTitleWidget,
        help_text="List students whose parents have had rejected permission for low risk excursions.",
        required=False,
    )

src/profiles/views.py
import re
import codecs
import csv

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.http import Http404

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Profile
from .forms import UserImportForm, PermissionForm


######################################
#
#   PROFILE VIEWS
#
######################################
# class ProfileList(ListView):
#     model = Profile

@staff_member_required()
def reset_password_to_default(request, id):
    student = get_object_or_404(User, id=id)
    this_user = request.user

    if student.profile.homeroom_teacher == this_user or this_user.is_superuser:
        student.password = make_password("wolf")
        student.save()
        messages.success(request, "Password has been reset to \"wolf\" for %s." % student.get_full_name())
        return redirect('events:registrations_homeroom')
    else:
        raise Http404("You are not this student's homeroom teacher.")


@user_passes_test(lambda u: u.is_superuser)
def mass_update(request):

    new_staff_list = []
    new_student_list = []
    student_errors = []
    staff_errors = []
    staff_import = False
    student_import = False
    num_deactivated = 0
    form = UserImportForm(request.POST or None, request.FILES or None)

    # positions_to_import = ["TEACHER", "VICE-PRINCIPAL", "PRINCIPAL", "EA", "TOC", "DIST YOUTH WRK", "DIST YOUTH WRK", "CERLICAL"]  
    positions_to_import = ["TOC", "Administrator", "Secretary", "Counsellor", "EA", "Support", "SD72 Student Teacher", "Teacher"]
    # currently not included: ED ASSISTANT, IT TECHNICIAN, CUSTODIAL
    grades_to_ignore = ["AD", "HS", "RG", "NS"]  # Adult grad, Home Schooled, Returning Grad, Non Student

    if form.is_valid():
        if 'staff_csv_file' in request.FILES:
            file = request.FILES['staff_csv_file']
            reader = csv.reader(codecs.iterdecode(file, 'utf-8-sig'))
            staff_import = True
            for row in reader:
                # check for blank rows, proper number of fields, and staff positions
                if row and len(row) == 5 and row[3] in positions_to_import:
                    try:
                        username = int(row[0])  # will throw an error if not an integer, including for header row
                    except ValueError:  # ID is not an integer
                        pass

                    qs = User.objects.all()

                    # check if user exists, else create new user
                    if username and not qs.filter(username=username).exists():
                        user = User.objects.create_user(
                            username=username,
                            password="tyee",
                            first_name=row[1].strip().upper(),
                            last_name=row[2].strip().upper(),
                            # row[3] is staff type (TOC, Teacher,)
                            email=row[4].strip(),
                            is_staff=True,
                        )
                        new_staff_list.append(user)


        if 'student_csv_file' in request.FILES:
            update_start_time = timezone.now()

            file = request.FILES['student_csv_file']
            semester = form.cleaned_data['semester']

            reader = csv.reader(codecs.iterdecode(file, 'utf-8-sig'))
            student_import = True
            count = 0

            users_qs = User.objects.all()

            # important columns in csv
            # student_number_heading = "Login Student Number"
            # sn_regex_string = r"^(9[789])(\d{5})$"  # 7 digits beginning in 99 98 or 97
            first_name_heading = "UsualFirst"
            last_name_heading = "UsualLast"
            grade_heading = "Grade"
            email_heading = "Email1"
            homeroom_teacher_heading = "HR Teacher"
            phone_heading = "CellPhone"
            contact_email_heading = "Email1"
            

            # student_number_col = None
            first_name_col = None
            last_name_col = None
            email_col = None
            homeroom_teacher_col = None
            phone_col = None
            contact_email_col = None
            grade_col = None

            for row in reader:

                # skip empty rows and rows without proper number of fields
                if row and len(row) >= 7:


                    if email_heading in row:  # Heading row
                        try:
                            # student_number_col = row.index(student_number_heading)
                            first_name_col = row.index(first_name_heading)
                            last_name_col = row.index(last_name_heading)
                            email_col = row.index(email_heading)
                            homeroom_teacher_col = row.index(homeroom_teacher_heading)
                            phone_col = row.index(phone_heading)
                            contact_email_col = row.index(contact_email_heading)
                            grade_col = row.index(grade_heading)
                        except ValueError:
                            student_errors.append({'error': "Expected column header not found", 'row': row})
                            break

                    else:  # Student data row
                        if not email_col:  # then we haven't got a header row yet
                            student_errors.append({'error': "Heading row not found", 'row': row})
                            break

                        # Get username from student email and check if the user exists
                        email = row[email_col].strip()
                        username = email.lower()
                        # username = email.split("@")[0].strip().lower()
                        first_name = row[first_name_col].strip().upper()
                        last_name = row[last_name_col].strip().upper()
                        homeroom_teacher = row[homeroom_teacher_col].strip()
                        # student_number = row[student_number_col].strip()
                        phone = row[phone_col].strip()
                        contact_email = row[contact_email_col].strip()
                        grade = row[grade_col].strip()

                        if grade in grades_to_ignore:
                            # skip these students
                            continue

                        # validate username/email
                        if not username:
                            student_errors.append({'error': "No email/username found for student.  Account not created.", 'row': row})
                            break

                        # validate student number
                        # if not re.match(sn_regex_string, student_number):
                        #     student_errors.append({'error': "Student number doesn't match 99 pattern", 'row': row})

                        # validate homeroom teacher
                        if homeroom_teacher:  # if they don't have one field will be blank string ''
                            try:  # sometimes homeroom id shows up as 0, which doesn't exist
                                # print(homeroom_teacher)
                                last, first_init = homeroom_teacher.split(";")[0].split(",")  # multiple seperated by ; so just take first: "smooth, t; smith, j"
                                last = last.strip().upper()
                                first_init = first_init.strip().upper()

                                homeroom_teacher = User.objects.filter(is_staff=True).get(last_name=last, first_name__startswith=first_init)
                            except User.DoesNotExist:
                                student_errors.append({'warning': "Homeroom teacher with ID '" + homeroom_teacher +
                                                                    "' not recognized", 'row': row})
                                homeroom_teacher = None
                        else:
                            homeroom_teacher = None

                        # clean grade
                        if not grade:  # needs an int so empty string is bad
                            grade = None
                        else:
                            try:
                                int(grade)
                            except ValueError:  # grade is text, not an integer
                                student_errors.append({'warning': "Grade not recognized", 'row': row})
                                grade = None

                        # change blank strings to None
                        if not phone:
                            phone = None
                        if not contact_email:
                            contact_email = None

                        
                        # Check if user exists with first.last as username
                        user, created = User.objects.get_or_create(
                            username=username,
                        )

                        if created:
                            user.set_password("tyee")
                            user.save()
                            new_student_list.append(user.id)  
                        
                        # We have a user object now.  Update names and set active:
                        user.is_active = True
                        user.first_name = first_name
                        user.last_name = last_name
                        user.save()

                        # A profile is created automatically when a new user is created.  Update it.
                        # But sometimes errors cause a user to be created without a profile.  So just in case:

src/profiles/templates/profiles/permission_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
    <!-- form.media -->
    {{ form.media.css }}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock style %}

{% block head_title %}Permissions | {{ block.super }}{% endblock %}

{% block content %}

    <h1>Student Permanent Permission Updates</h1>

    <form method="POST" action=""> {% csrf_token %}
        {{ form|crispy }}
{#        <div class="btn-group pull-right" role="group">#}

            {#          <a class="btn btn-default" href="{% url 'prof:excuse_list' %}">Cancel</a>#}
            <input class="btn btn-primary" type="submit" value="Save"/>
{#        </div>#}
    </form>


    <hr>
    <h3 class="pull-left">Current Permissions Status</h3>

    <table data-toolbar="#toolbar"
           data-toggle="table"
           data-classes="table table-hover table-no-bordered table-condensed"
           data-search="true"
           data-id-field="id"
           data-sort-name="last"
           data-sort-order="asc"
           id="table">
        <thead>
        <tr>
            <th data-field="id" data-sortable="true">Username</th>
            <th data-field="first" data-sortable="true">First Name</th>
            <th data-field="last" data-sortable="true">Last Name</th>
            <th data-field="grade" data-sortable="true">Grade</th>
{#            <th data-field="homeroom" data-sortable="true">Homeroom</th>#}
            <th data-field="permission" data-sortable="true">Permission</th>
        </tr>
        </thead>
        <tbody>
        {% for student in student_list %}
            <tr class="{% if student.permission is None %}
                    warning
                    {% elif student.permission is True %}
                    success
                    {% else %}
                    danger
                    {% endif %}
                ">
                <td>{{ student.user.username }}</td>
                <td>{{ student.user.first_name }}</td>
                <td>{{ student.user.last_name }}</td>
                <td>{{ student.grade }}</td>
{#                <td>{{ student.homeroom_teacher}}</td>#}
                <td>{{ student.permission|yesno:"Yes,No,Incomplete" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock content %}

{% block js %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Bootstrap Tables:  http://bootstrap-table.wenzhixin.net.cn/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>

    {{ form.media.js }}
{%  endblock %}

src/profiles/templates/profiles/profile_imports.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}{% endblock style %}

{% block head_title %}User Import | {{ block.super }}{% endblock %}

{% block content %}


  <h1>Mass User Import/Update</h1>

  <div class="panel panel-primary">
    <div class="panel-heading">Bulk Import Form</div>
    <div class="panel-body">
      <form  enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Import" />
      </form>
    </div>
  </div>



  {% if staff_import %}
    <h3>Staff Import Results</h3>
    <p>New staff imported: {{ new_staff_list|length }}</p>
    <p>The following new users were imported.  Their default password has been set to "wolf".</p>

    <table class="table table-no-bordered">
      <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
      </tr>
      </thead>
      <tbody>
      {% for obj in new_staff_list %}
        <tr>
          <td>{{ obj.username }}</td>
          <td>{{ obj.first_name }}</td>
          <td>{{ obj.last_name }}</td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if student_import %}
    <h3>Student Import Results</h3>
    <p>Inactive students: {{ num_deactivated }}</p>
    <h4>Import Errors and Warnings</h4>
    <p>Total errors/warnings: {{ student_errors|length }}</p>
    <p>Errors will appear in red and prevent students from being imported.  Warnings appear in yellow and do not
    prevent import, but you might need to manually fix something.</p>
      <table class="table table-no-bordered">
        <thead>
        <tr>
          <th>Count</th>
          <th>Error/Warning</th>
          <th>Row</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in student_errors %}
          <tr class="{% if obj.error %}danger{% elif obj.warning %}warning{% elif obj.info %}info{% endif %}">
            <td>{{ forloop.counter }}</td>
            <td>{{ obj.error }}{{ obj.warning }}{{obj.info}}</td>
            <td>{{ obj.row }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    <h4>Successful Imports</h4>
    <p>New students imported: {{ new_student_list|length }}</p>
    <p>The following new users were imported.  Their default password has been set to "wolf".</p>

    <table class="table table-no-bordered">
      <thead>
      <tr>
        <th>Count</th>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Homeroom Teacher</th>
        <th>Grade</th>
        <th>Phone</th>
        <th>Email</th>
      </tr>
      </thead>
      <tbody>
      {% for obj in new_student_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ obj.username }}</td>
          <td>{{ obj.first_name }}</td>
          <td>{{ obj.last_name }}</td>
          <td>{{ obj.profile.homeroom_teacher.profile}}</td>
          <td>{{ obj.profile.grade }}</td>
          <td>{{ obj.profile.phone }}</td>
          <td>{{ obj.profile.email }}</td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% endif %}

{% endblock content %}

src/profiles/templates/profiles/profile_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}{% endblock style %}

{% block head_title %}Users | {{ block.super }}{% endblock %}

{% block content %}


    <h1>Student List</h1>
  <a class="btn btn-warning" href="{% url 'profiles:mass_update' %}">MASS IMPORT</a>
  <ul>
      {% for profile in object_list %}
          <li>{{ profile}},{{ profile.user.username }}, {{ profile.user.date_joined }}, {{ profile.homeroom_teacher }}</li>
      {% endfor %}
  </ul>

{% endblock content %}