src/events/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = "events"

urlpatterns = [
    url(r'^$', views.event_list, name='home'),
    url(r'^$', views.event_list, name='list'),
    url(r'^list/$', views.event_list, name='list'),
    url(r'^block/all/$', views.event_list, name='list'),
    url(r'^old', views.event_list, name='list_old'),
    url(r'^block/(?P<block_num>\d+)/$', views.event_list, name='list_by_block'),
    url(r'^export/$', views.event_list_export, name='export'),
    url(r'^manage/$', views.event_manage, name='manage'),
    url(r'^create/$', views.event_create, name='create'),
    url(r'^(?P<id>\d+)/$', views.event_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.event_update, name='update'),
    url(r'^(?P<id>\d+)/copy/$', views.event_copy, name='copy'),
    # url(r'^(?P<id>\d+)/delete/$', views.event_delete, name='delete'),
    url(r'^(?P<pk>\d+)/delete/$', views.EventDelete.as_view(), name='delete'),
    url(r'^(?P<id>\d+)/attendance/$', views.event_attendance, name='attendance'),
    url(r'^(?P<id>\d+)/attendance/keypad/$', views.event_attendance_keypad, name='attendance_keypad_init'),
    url(r'^(?P<id>\d+)/attendance/keypad/disable$', views.event_attendance_keypad_disable, name='attendance_keypad_disable'),
    url(r'^(?P<id>\d+)/attendance/block/(?P<block_id>\d+)/$', views.event_attendance, name='attendance_by_block'),
    url(r'^staff/$', views.staff_locations, name='staff_locations'),
    url(r'^staff/overview/$', views.staff_overview, name='staff_overview'),
    url(r'^synervoice/$', views.synervoice, name='synervoice'),
    url(r'^stats/$', views.stats2, name='stats'),
    url(r'^stats2/$', views.stats2, name='stats2'),
    url(r'^stats_to_date/$', views.stats_to_date, name='stats_to_date'),
    url(r'^stats/staff/$', views.stats_staff, name='stats_staff'),


    # Locations
    url(r'^locations/create/$', views.location_create, name='location_create'),
    url(r'^ajax/validate_location/$', views.validate_location, name='validate_location'),


    # Registrations
    url(r'^register/(?P<id>\d+)/block/(?P<block_num>\d+)/$', views.register, name='register'),
    url(r'^registrations/$', views.registrations_list, name='registrations_list'),
    url(r'^registrations/(?P<id>\d+)/delete$', views.registrations_delete, name='registrations_delete'),
    url(r'^registrations/all/$', views.registrations_all, name='registrations_all'),
    url(r'^registrations/homeroom/$', views.registrations_homeroom, name='registrations_homeroom'),
    url(r'^registrations/homeroom/(?P<employee_number>\d+)/$', views.registrations_homeroom, name='registrations_homeroom'),
    url(r'^registrations/manage/$', views.registrations_manage, name='registrations_manage'),
    # url(r'^registrations/user/(?P<username>\w+)/$', views.registrations_user, name='registrations_user'),
    path('registrations/user/<str:username>/', views.registrations_user, name='registrations_user')
    # url(r'^registrations/homeroom/$', views.homeroom, name='homeroom'),

]

src/excuses/urls.py
from django.conf.urls import url

from excuses import views

app_name = "excuses"

urlpatterns = [
    url(r'^all/$', views.excuse_list, name='excuse_list'),
    url(r'^create/$', views.excuse_create, name='excuse_create'),
    url(r'^(?P<id>\d+)/edit/$', views.excuse_edit, name='excuse_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.ExcuseDelete.as_view(), name='excuse_delete'),

]

src/flex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from events import views as event_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

app_name = "flex"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', event_views.event_list, name='home'),
    # installed apps
    # url(r'^summernote/', include('django_summernote.urls')),
    # url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^select2/', include('django_select2.urls')),
    # custom apps
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^excuses/', include(('excuses.urls', 'excuses'), namespace='excuses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url

from . import views

app_name = "profiles"

urlpatterns = [
    # url(r'^$', views.ProfileList.as_view(), name='list'),
    # url(r'^import/$', views.mass_user_import, name='import'),
    url(r'^update/mass/$', views.mass_update, name='mass_update'),
    url(r'^(?P<id>\d+)/reset/$', views.reset_password_to_default, name='reset_password'),
    url(r'^permissions/update/$', views.permissions_update, name='permissions_update'),

]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <!-- ****** faviconit.com favicons ****** -->
	<link rel="shortcut icon" href="/static/icons/favicon.ico">
	<link rel="icon" sizes="16x16 32x32 64x64" href="/static/icons/favicon.ico">
	<link rel="icon" type="image/png" sizes="196x196" href="/static/icons/favicon-192.png">
	<link rel="icon" type="image/png" sizes="160x160" href="/static/icons/favicon-160.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/static/icons/favicon-96.png">
	<link rel="icon" type="image/png" sizes="64x64" href="/static/icons/favicon-64.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/static/icons/favicon-32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/static/icons/favicon-16.png">
	<link rel="apple-touch-icon" href="/static/icons/favicon-57.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/static/icons/favicon-114.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/static/icons/favicon-72.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/static/icons/favicon-144.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/static/icons/favicon-60.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/static/icons/favicon-120.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/static/icons/favicon-76.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/static/icons/favicon-152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/favicon-180.png">
	<meta name="msapplication-TileColor" content="#FFFFFF">
	<meta name="msapplication-TileImage" content="/static/icons/favicon-144.png">
	<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
	<!-- ****** faviconit.com favicons ****** -->

  <script src="https://use.fontawesome.com/fe7c928d9c.js"></script>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Bootstrap Tables:  http://bootstrap-table.wenzhixin.net.cn/ -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css">

  <title>{% block head_title %}Carihi Win{% endblock %}</title>
  <link rel="stylesheet" href="{%  static 'css/base-v1.1.css' %}">

  {% block style %}{% endblock style %}

</head>
<body>


{% include "navbar.html" %}

<div class="container">
  {% include "messages_display.html" %}
  {% block content %}
  {% endblock content %}

    <!-- Modal: http://getbootstrap.com/javascript/#modals -->
  {% if not request.user.is_authenticated and not "/accounts/login/" in request.get_full_path %}
    {% include "login_modal.html" %}
  {% endif %}

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Make sure this comes before bootstrap.js so that bootstrap takes precedent -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>
$(document).ready(function() {

  // http://stackoverflow.com/questions/24514717/bootstrap-navbar-active-state-not-working
  $('.navbar-nav li.active').removeClass('active');
  $('a[href="' + location.pathname + '"]').closest('li').addClass('active');

  //set the cursor to loading/wait cursor right before page changes.  Cursor provides feedback as sometimes generating
  // data for the new page can take a second or two.
  $(window).on('beforeunload', function(){
   $('*').css("cursor", "wait");
  });

  // close message alerts that appear at the top of the page sometimes as feedback.
  $("div.alert.slide").on("click", "button.close", function() {
    $(this).parent().slideUp();
  });

  {% if not request.user.is_authenticaed and not "/accounts/login/" in request.get_full_path %}
    if(!sessionStorage.showLoginModal) // if the session cookie exists, don't show.
    $('#login-modal')
      .modal('show') // show the login modal
      .on('shown.bs.modal', function () {
        $('.autofocus').focus()
      })
      .on('hidden.bs.modal', function (e) {
        sessionStorage.showLoginModal = false // don't show again this session.
      });
  {% endif %}


});
</script>

{% block js %}{% endblock js %}

</body>
</html>

src/templates/login_modal.html
<!-- Modal: http://getbootstrap.com/javascript/#modals -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="login-modal-label">Log in?</h4>
      </div>
      <div class="modal-body clearfix">
        <p>To register for events you need to log in first.
          If you just want to browse events, you don't have to.
          You can also log in using the <i class="fa fa-bars visible-xs-inline"></i> menu at the top right</p>
          <p><b>Username change:</b> student usernames have been changed to the same firstname.lastname as your regular school log in. 
            Staff usernames are still their employee number.</p>
            <form method="POST" action="{% url 'auth_login' %}">{%  csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control autofocus" name="username" placeholder="Username" />
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Password" />
            </div>
           <div class="pull-right">
            <button type="button" class="btn btn-default" data-dismiss="modal">No thanks</button>
            <button type="submit" class="btn btn-primary">Log in</button>
           </div>
        </form>
      </div>

    </div>
  </div>
</div>

src/templates/messages_display.html
<div class="messages">
  {% if messages %}
    {% for message in messages %}
      <div role="alert"
           class="slide alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        <button type="button" class="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message|safe }}
      </div>
    {% endfor %}
  {% endif %}
</div>

src/templates/navbar.html
{% load staticfiles %}
{% load utility_tags %}

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.sd72.bc.ca/carihi/">
        <img alt="Brand" src="{%  static 'img/logo-80px.png' %}">
      </a>
      <a href="http://www.sd72.bc.ca/carihi/"  class="navbar-brand hidden-sm">Carihi Secondary</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    {% if user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'events:list' %}">All Events<span class="sr-only">(current)</span></a>
        </li>

          {% if request.user.is_staff %}
            <li>
              <a href="{% url 'events:manage' %}">Your Events<span class="sr-only"></span></a>
            </li>

            <li>
              <a href="{% url 'events:registrations_homeroom' %}">Homeroom<span class="sr-only"></span></a>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'events:staff_locations' %}">All Staff<span class="sr-only"></span></a>
                    </li>
                    <li>
                        <a href="{% url 'events:registrations_all' %}">All Students<span class="sr-only"></span></a>
                    </li>
                    <li>
                        <a href="{% url 'events:stats' %}">Event Stats<span class="sr-only"></span></a>
                    </li>
                </ul>
            </li>

          {% else %}
            <li>
              <a href="{% url 'events:registrations_manage' %}">Your Events<span class="sr-only"></span></a>
            </li>
          {% endif %}

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true" aria-expanded="false">Links <span class="caret"></span></a>
            <ul class="dropdown-menu">
                {% menu_list %}
                {% if request.user.is_superuser %}
                    <li role="separator" class="divider"></li>
                    <li><a href="/admin/utilities/menuitem/"><i class="fa fa-fw fa-pencil"></i>&nbsp;&nbsp;Edit this list</a></li>
                {% endif %}
            </ul>
          </li>

      </ul>
      {% endif %}

      {% if not request.user.is_authenticated and not "/accounts/login/" in request.get_full_path %}
      <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{%  csrf_token %}
        <div class="input-group input-group-unified input-group-sm">
          <input type="text" class="form-control" name="username" placeholder="Username" autofocus />
          <input type="password" class="form-control" name="password" placeholder="Password" />
          <span class="input-group-btn"><button type="submit" class="btn btn-default">Login</button></span>
        </div>
      </form>

      {% endif %}
      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_superuser %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'events:stats_staff' %}">Staff Stats</a></li>
                <li><a href="{% url 'events:stats_to_date' %}">Student Attendance to Date</a></li>
                <li role="separator" class="divider"></li>
               <li><a href="{% url 'profiles:permissions_update' %}">Permission Forms</a></li>
              <li><a href="{% url 'excuses:excuse_list' %}">Excused Students</a></li>
              <li><a href="{% url 'profiles:mass_update' %}">Bulk User Import</a></li>
              <li><a href="{% url 'events:synervoice' %}">School Messenger</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/admin">Database Management</a></li>
            </ul>
          </li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false">{{ request.user.get_full_name|upper }}
             <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'auth_logout' %}?next={% url 'home' %}">Logout</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
          </ul>
        </li>

      </ul>
      {% endif %}

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>