src/excuses/urls.py
from django.conf.urls import url

from excuses import views

app_name = "excuses"

urlpatterns = [
    url(r'^all/$', views.excuse_list, name='excuse_list'),
    url(r'^create/$', views.excuse_create, name='excuse_create'),
    url(r'^(?P<id>\d+)/edit/$', views.excuse_edit, name='excuse_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.ExcuseDelete.as_view(), name='excuse_delete'),

]

src/flex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from events import views as event_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

app_name = "flex"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', event_views.event_list, name='home'),
    # installed apps
    # url(r'^summernote/', include('django_summernote.urls')),
    # url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^select2/', include('django_select2.urls')),
    # custom apps
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^excuses/', include(('excuses.urls', 'excuses'), namespace='excuses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/events/models.py
import mimetypes
import urllib
from datetime import date, timedelta, datetime
from enum import Enum

import embed_video
import os

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.db import OperationalError, models
from django.urls import reverse
from django.db.models.signals import post_save
from django.utils import timezone

from embed_video.backends import detect_backend, UnknownBackendException

# Create your models here.
from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFill, SmartResize, ResizeToFit

from excuses.models import Excuse
from flex.utils import default_event_date


class CoreCompetency(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    link = models.URLField()
    icon = models.ImageField(null=True, blank=True, upload_to="icons/")

    class Meta:
        verbose_name_plural = "Core Competencies"

    def __str__(self):
        return self.name


class Category(models.Model):
    COLOR_CHOICES = (  # From bootstrap classes/highlighting
        (None, 'None'),
        ('warning', 'Yellow'),
        ('success', 'Green'),
        ('info', 'Blue'),
        ('danger', 'Red'),
    )
    DEFAULT_CATEGORY_ID = 1
    name = models.CharField(max_length=120)
    abbreviation = models.CharField(max_length=4)
    visible_in_event_list = models.BooleanField(default=False)
    sort_priority = models.IntegerField(default=0)
    color = models.CharField(max_length=10, choices=COLOR_CHOICES, default=None, blank=True, null=True,
                             help_text="Events will be highlighted with this color in the events list",)
    description = models.CharField(max_length=512, blank=True, null=True)

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['-sort_priority']

    def __str__(self):
        return self.name

    @classmethod
    def get_default(cls):
        try:
            if cls.objects.filter(name="Support").exists():
                return cls.objects.get(name="Support")
            else:
                return cls.objects.all().first()
        except OperationalError:
            pass  # tables don't exist, could happen when creating a new environment
            


class Location(models.Model):
    room_number = models.CharField(max_length=20, unique=True, help_text="e.g. B201")
    name = models.CharField(max_length=120, null=True, blank=True, help_text="e.g. Hackerspace (or) Couture's Room")

    def __str__(self):
        return self.room_number

    def get_name(self):
        if self.name:
            return self.name
        else:
            return ""

    def get_detailed_name(self):
        name_str = self.room_number
        if self.name:
            name_str += " (" + self.name + ")"
        return name_str

    def get_name_with_conflicts(self, date):
        events = self.event_set.filter(date=date)
        return self.get_detailed_name() + "" + str(events)

    class Meta:
        ordering = ['room_number']


class BlockManager(models.Manager):

    def get_flex_1(self):
        return self.active()[0]

    def get_flex_2(self):
        if not self.single_block():
            return self.active()[1]
        else:
            return None

    def single_block(self):
        """Check if the site is set up with only a single block, returns True or False
        """
        return self.active().count() == 1

    def get_only(self):
        return self.active().first()


    def active(self):
        return self.get_queryset().filter(active=True)

    def get_by_num(self, block_num):
        """ Gets the 1st or second active block """
        if int(block_num) == 1:
            return self.get_flex_1()
        elif not self.single_block() and int(block_num) == 2:
            return self.get_flex_2()
        else:
            return ValueError ("block_num was not 1 or 2.  Only two active blocks are currently supported")

    def get_num_from_id(self, id):
        """ Given a block object's ID, return 1 or 2 if it is the
        1st or second active block """
        if id == self.get_flex_1().id:
            return 1
        elif not self.single_block() and id == self.get_flex_2().id:
            return 2
        else:
            return ValueError ("That block is not active.")


class Block(models.Model):
    name = models.CharField(max_length=20)
    start_time = models.TimeField()
    end_time = models.TimeField()
    active = models.BooleanField(default=True)

    objects = BlockManager()

    class Meta:
        ordering = ['start_time']

    def __str__(self):
        return self.name

    def constant_string(self):
        """ Return either  FLEX1 or FLEX2 based on whether this is the first or second active flex block
        as there should only be one or two"""
        if self == Block.objects.get_flex_1():
            return "FLEX1"
        else:
            return "FLEX2"

    def synervoice_absent_string(self):
        return "F" + str(self.id) + "-ABS"

    def synervoice_noreg_string(self):
        return "F" + str(self.id) + "-NOREG"

    def synervoice_noreg_string(self):
        return "F" + str(self.id) + "-PRESENT_OR_EXCUSED"


class EventManager(models.Manager):
    def all_for_date(self, event_date, block=None):
        if block:
            qs = block.event_set.all()
        else:
            qs = self.get_queryset()
        return qs.filter(date=event_date)

    def all_visible_on_date(self, date):
        return self.get_queryset().filter(date=date, category__visible_in_event_list=True)

    def all_for_facilitator(self, user):
        return user.event_set.all()

    def all_active(self):
        """ Only events with at least one active block """
        return self.get_queryset().filter(blocks__in=Block.objects.active())


class Event(models.Model):

    F1_XOR_F2 = 0
    F1_OR_F2 = 1
    F1_AND_F2 = 2
    MULTI_BLOCK_CHOICES = (
        (F1_XOR_F2, 'Can choose one or the other, but not both.'),
        (F1_OR_F2, 'Can choose one block or both blocks.'),
        (F1_AND_F2, 'Both blocks are required.'),
    )

    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)  # MCE widget validation fails if required
    # description_image_file = models.ImageField(upload_to='images/', null=True, blank=True)
    description_image_file = ProcessedImageField(upload_to='images/', null=True, blank=True,
                                                 processors=[ResizeToFit(400, 400, upscale=False)],
                                                 format='JPEG',
                                                 options={'quality': 80},
                                                 help_text="Upload an image directly from your computer.  You can also "
                                                           "get an image from the web by pasting a direct link to the "
                                                           "image in the Description link field below.",
                                                 verbose_name="Image",
                                                 )
    description_link = models.URLField(
        "Description link (image, video, file, or webpage)",
        null=True, blank=True,
        help_text="An optional link to provide with the text description. Links to videos (YouTube or Vimeo) "
                  "or an image (must end in .png, .jpg, or .gif) will be embedded within the description."
                  "If the link is to another web page or a file, it will just display the link.")

    category = models.ForeignKey(Category, default=Category.DEFAULT_CATEGORY_ID, on_delete=models.SET_NULL, null=True,
                                 help_text="By default, events are sorted by category in the events list.")
    competencies = models.ManyToManyField(CoreCompetency, blank=True,
                                          help_text="The Core Competencies relevant to this event.")
    date = models.DateField(default=default_event_date)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    blocks = models.ManyToManyField(Block, help_text="In which block(s) will this event occur?")
    multi_block_event = models.IntegerField(
        default=F1_OR_F2,
        choices=MULTI_BLOCK_CHOICES,
        help_text="If the event is running in more than one block, what restrictions are there for students?  "
                  "This field is ignored if the event only occurs during one block.")
    facilitators = models.ManyToManyField(User, related_name='events',
                                          limit_choices_to={'is_staff': True})
    allow_facilitators_to_modify = models.BooleanField(
        default=True,
        help_text="If false, only the creator of the event can edit.  If true, then any staff member that is listed as "
                  "a facilitator will be able to edit the event.  The creator will always be able to edit this event, "
                  "even if they are not listed as one of the facilitators.")
    registration_cut_off = models.DurationField(
        default=timedelta(days=0, hours=0, minutes=5, seconds=0),
        help_text="How long before the start of the event does registration close?  After this time, "
                  "students will no longer be able to register for the event, nor will they be able to delete it "
                  "if they've already registered.")
    allow_registration_after_event_has_started = models.BooleanField(
        default=False,
        help_text="Students can continue to register for this event after it has already started, for the amount of "
                  "time indicated in the 'Registration cut off time'.  For example, if your cut off time is set to "

src/excuses/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import Count

from flex.utils import default_event_date


class ExcuseReason(models.Model):
    reason = models.CharField(max_length=50)
    flex_activity = models.BooleanField(default=False, help_text="Check this if the student is still conducting"
                                                                 " an activity compliant with the Flex course.")

    def __str__(self):
        return self.reason

    class Meta:
        ordering = ['reason']


class ExcuseQuerySet(models.QuerySet):
    def date(self, date):
        return self.filter(first_date__lte=date, last_date__gte=date)

    def in_block(self, block):
        return self.filter(blocks=block)

    def in_blocks_exact(self, blocks):
        # https://stackoverflow.com/questions/16324362/django-queryset-get-exact-manytomany-lookup

        # print(len(blocks))
        # print(self)


        excuse_qs = self.annotate(count=Count('blocks')).filter(count=len(blocks))

        # print(excuse_qs)
        # for exc in excuse_qs:
        #     print(exc)
        #     print(exc.blocks)
        #     print("*********")

        for block in blocks:
            # print (block)
            excuse_qs = excuse_qs.filter(blocks=block)
            # print(excuse_qs)
        return excuse_qs

    def for_student(self, user):
        return self.filter(students=user)


class ExcuseManager(models.Manager):
    def get_queryset(self):
        return ExcuseQuerySet(self.model, using=self._db)

    def current(self, as_of_date=default_event_date()):
        """ Filters out excuses that have past (has an end date beyond the as_of_date)
        """
        return self.get_queryset().filter(last_date__gte=as_of_date)

    def all_on_date(self, date, block=None):
        qs = self.get_queryset().date(date)
        # qs.filter(blocks__id=block.id)
        # for excuse in qs:
        #     print(block)
        #     print(excuse.blocks.filter(active=True))

        return qs

    def students_excused_on_date(self, date, block, students=None):
        """
        :param date: excuses covering this date
        :param students: a queryset of students to check
        :param blocks: a queryset of Block objects
        :return: a queryset of students who are excused on this date, for the given blocks
        """

        # https://stackoverflow.com/questions/45062238/django-getting-a-list-of-foreign-key-objects
        if not students:
            students = User.objects.filter(is_active=True, is_staff=False)

        return students.filter(excuse__in=self.get_queryset().date(date).in_block(block))


class Excuse(models.Model):
    students = models.ManyToManyField(User, limit_choices_to={'is_staff': False})
    reason = models.ForeignKey(ExcuseReason, on_delete=models.SET_NULL, null=True)
    first_date = models.DateField(
        default=default_event_date,
        help_text="This is the first date that the student is excused for the provided reason."
    )
    last_date = models.DateField(
        default=default_event_date,
        help_text="This is the last date that the student is excused for the provided reason."
    )
    blocks = models.ManyToManyField('events.Block', help_text="In which block(s) are the students excused?")

    objects = ExcuseManager()

    def __str__(self):
        return "%s from %s to %s" % (self.reason, self.first_date, self.last_date)

    class Meta:
        ordering = ['-first_date']

src/excuses/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.db.models import Prefetch
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView

from excuses.forms import ExcuseForm
from excuses.models import Excuse
from flex.utils import default_event_date


@staff_member_required
def excuse_list(request, block_id=None):
    date_query = request.GET.get("date", str(default_event_date()))
    d = datetime.strptime(date_query, "%Y-%m-%d").date()

    queryset = Excuse.objects.current(d).prefetch_related(
        Prefetch('students', queryset=User.objects.order_by('last_name')),
        'reason')
    # queryset = Excuse.objects.all()
    # queryset.prefetch_related('students', 'blocks')
    context = {
        "date_filter": date_query,
        "date_object": d,
        "object_list": queryset,
    }
    return render(request, "excuses/excuse_list.html", context)


@staff_member_required
def excuse_create(request):
    form = ExcuseForm(request.POST or None)

    if form.is_valid():
        excuse = form.save()
        excuse.save()

        msg = "New excuse list created for <i>%s</i> from: %s to %s" % \
              (excuse.reason, excuse.first_date, excuse.last_date)

        messages.success(request, msg)

        return redirect('excuses:excuse_list')

    context = {

        "title": "Excuse Students",
        "form": form,
        "btn_value": "Save"
    }
    return render(request, "excuses/excuse_form.html", context)


@staff_member_required
def excuse_edit(request, id):
    instance = get_object_or_404(Excuse, id=id)

    form = ExcuseForm(request.POST or None, instance=instance)

    if form.is_valid():
        excuse = form.save()
        excuse.save()
        msg = "Excuse list updated for <i>%s</i> from: %s to %s" % \
              (excuse.reason, excuse.first_date, excuse.last_date)
        messages.success(request, msg)
        return redirect('excuses:excuse_list')

    context = {
        "title": "Edit Excused Students",
        "form": form,
        "btn_value": "Update",
        "delete_btn": True,
        "excuse": instance,
    }
    return render(request, "excuses/excuse_form.html", context)


@method_decorator(staff_member_required, name='dispatch')
class ExcuseDelete(DeleteView):
    model = Excuse
    success_url = reverse_lazy('excuses:excuse_list')

src/excuses/templates/excuses/excuse_confirm_delete.html
{% extends "base.html" %}

{% block head_title %}Delete Excuse | {{ block.super }}{% endblock %}

{% block content %}
  <h1>Confirm Deletion of Excuse # {{ object.id }}</h1>

  <p>Are you sure you want to delete this excuse?</p>
    <ul>
        <li>Start: {{ object.first_date}}</li>
        <li>End: {{ object.last_date}}</li>
        <li>Blocks:
            <ul>{{ excuse.blocks.all|unordered_list}}</ul>
        </li>
        <li>{{ object.reason }}</li>
        <li>Students:
            <ul>
                {% for student in object.students.all %}
                    <li>{{ student.get_full_name }};</li>
                {% endfor %}
            </ul>
        </li>
    </ul>


  <form method="post">{% csrf_token %}
    <a href="{% url 'excuses:excuse_list' %}" class="btn btn-default">Cancel</a>
    <input type="submit" class="btn btn-danger" value="Delete" />
  </form>


{% endblock content %}

src/excuses/templates/excuses/excuse_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block style %}
  <!-- form.media -->
  {{ form.media.css }}

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock style %}

{% block content %}
  <div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6">

      <form method="POST" action=""> {% csrf_token %}
        <h1 class="clearfix">{{ title }}
          <div class="btn-group pull-right" role="group">

            <a class="btn btn-default" href="{% url 'excuses:excuse_list' %}">Cancel</a>
            <input class="btn btn-primary" type="submit" value="{{ btn_value }}"/>
            {% if delete_btn %}<a class="btn btn-danger" href="{% url 'excuses:excuse_delete' excuse.id %}">Delete</a>{% endif %}

          </div>
        </h1>
        {{ form|crispy }}
        <div class="btn-group pull-right" role="group">

          <a class="btn btn-default" href="{% url 'excuses:excuse_list' %}">Cancel</a>
          <input class="btn btn-primary" type="submit" value="{{ btn_value }}"/>
          {% if delete_btn %}<a class="btn btn-danger" href="{% url 'excuses:excuse_delete' excuse.id %}">Delete</a>{% endif %}

        </div>
      </form>


    </div>

  </div>
  <br/>


{% endblock content %}

{% block js %}
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  {{ form.media.js }}
  <script id="event-datepicker" data-date-input-id="id_date" src="{% static 'js/events-datepicker-v3.js' %}"></script>

  <script>
    function WednesdaysOnly(date) {
      var day = date.getDay();
    // if (day != 3 && day != 0 && day != 6) // no Sat, Sun, or Wed
    if (day == 3) //Wednesday = 3
        return [true]
      else
        return [false]
    }

    $(document).ready(function () {
      var $dateInput1 = $("#id_first_date");
      var $dateInput2 = $("#id_last_date");

      $dateInput1.datepicker({
        dateFormat: 'yy-mm-dd',
        showOtherMonths: true,
        selectOtherMonths: true,
        beforeShowDay: WednesdaysOnly,
      });

      $dateInput2.datepicker({
        dateFormat: 'yy-mm-dd',
        showOtherMonths: true,
        selectOtherMonths: true,
        beforeShowDay: WednesdaysOnly,
      });

    });
  </script>
{% endblock js %}

src/excuses/templates/excuses/excuse_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/events.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock style %}

{% block head_title %}Excused | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-7">
          <h1>Excused Students List <small class="responsive-wrap">{{ date_object }}</small></h1>
          <div class="hidden-print">{%  include 'events/date_filter.html' %}</div>
        </div>
        <div class="col-md-5">
            <h1><div class="pull-right hidden-print">
              <a class="btn btn-success" href="{% url 'excuses:excuse_create' %}">
                <i class="fa fa-plus-circle"></i> Create New Excuse
              </a>
            </div></h1>
        </div>
    </div>



    <table data-toggle="table"
           data-classes="table table-no-bordered table-hover"
           data-search="true"
           data-sort-name="last_date"
           data-sort-order="desc"
           id="table">

        <thead>
        <tr>
            <th>Actions</th>
            <th data-field="first_date" data-sortable="true" data-sorter="dateSorter">Start</th>
            <th data-field="last_date" data-sortable="true" data-sorter="dateSorter">End</th>
            <th data-field="blocks" data-sortable="true">Blocks</th>
            <th data-field="reason" data-sortable="true">Reason</th>
            <th data-field="flex_activity" data-sortable="true">Flex Activity</th>
            <th data-field="students">Students</th>
        </tr>
        </thead>
        <tbody>
        {% for excuse in object_list %}
            <tr>
                <td>
                    <a href="{% url 'excuses:excuse_edit' excuse.id %}">Edit</a>
                </td>
                <td>{{ excuse.first_date }}<span style="display:none;">{{ excuse.first_date|date:'Ymd' }}</span></td>
                <td>{{ excuse.last_date }}<span style="display:none;">{{ excuse.first_date|date:'Ymd' }}</span></td>
                <td>
                    <small>
                        {% for block in excuse.blocks.all %}
                            {{ block }};
                        {% endfor %}
                    </small>
                </td>
                <td>{{ excuse.reason }}</td>
                <td>{{ excuse.reason.flex_activity|yesno }}</td>
                <td>
                    <small>
                        {% for student in excuse.students.all %}
                            {{ student.get_full_name }};
                        {% endfor %}
                    </small>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

{% block js %}

    {#  Date Filter#}
    <script src="{% static 'js/events-datepicker-v3.js' %}"></script>


    <!-- Bootstrap Tables:  http://bootstrap-table.wenzhixin.net.cn/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>

    <script>
        function dateSorter(a, b) {
            // need to pull 8 digit date out of this part of a,b: <div>YYYYMMDD</div>
            var re = /\d{6}/; // max 6 digits from 0-9
            var dateA = a.match(re); // first element is the match
            var dateB = b.match(re); // first element is the match

            dateA = dateA == null ? 0 : dateA[0];
            dateB = dateB == null ? 0 : dateB[0];

            if (dateA > dateB) return 1;
            if (dateA < dateB) return -1;
            return 0;
        }
    </script>
{% endblock %}