src/events/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = "events"

urlpatterns = [
    url(r'^$', views.event_list, name='home'),
    url(r'^$', views.event_list, name='list'),
    url(r'^list/$', views.event_list, name='list'),
    url(r'^block/all/$', views.event_list, name='list'),
    url(r'^old', views.event_list, name='list_old'),
    url(r'^block/(?P<block_num>\d+)/$', views.event_list, name='list_by_block'),
    url(r'^export/$', views.event_list_export, name='export'),
    url(r'^manage/$', views.event_manage, name='manage'),
    url(r'^create/$', views.event_create, name='create'),
    url(r'^(?P<id>\d+)/$', views.event_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.event_update, name='update'),
    url(r'^(?P<id>\d+)/copy/$', views.event_copy, name='copy'),
    # url(r'^(?P<id>\d+)/delete/$', views.event_delete, name='delete'),
    url(r'^(?P<pk>\d+)/delete/$', views.EventDelete.as_view(), name='delete'),
    url(r'^(?P<id>\d+)/attendance/$', views.event_attendance, name='attendance'),
    url(r'^(?P<id>\d+)/attendance/keypad/$', views.event_attendance_keypad, name='attendance_keypad_init'),
    url(r'^(?P<id>\d+)/attendance/keypad/disable$', views.event_attendance_keypad_disable, name='attendance_keypad_disable'),
    url(r'^(?P<id>\d+)/attendance/block/(?P<block_id>\d+)/$', views.event_attendance, name='attendance_by_block'),
    url(r'^staff/$', views.staff_locations, name='staff_locations'),
    url(r'^staff/overview/$', views.staff_overview, name='staff_overview'),
    url(r'^synervoice/$', views.synervoice, name='synervoice'),
    url(r'^stats/$', views.stats2, name='stats'),
    url(r'^stats2/$', views.stats2, name='stats2'),
    url(r'^stats_to_date/$', views.stats_to_date, name='stats_to_date'),
    url(r'^stats/staff/$', views.stats_staff, name='stats_staff'),


    # Locations
    url(r'^locations/create/$', views.location_create, name='location_create'),
    url(r'^ajax/validate_location/$', views.validate_location, name='validate_location'),


    # Registrations
    url(r'^register/(?P<id>\d+)/block/(?P<block_num>\d+)/$', views.register, name='register'),
    url(r'^registrations/$', views.registrations_list, name='registrations_list'),
    url(r'^registrations/(?P<id>\d+)/delete$', views.registrations_delete, name='registrations_delete'),
    url(r'^registrations/all/$', views.registrations_all, name='registrations_all'),
    url(r'^registrations/homeroom/$', views.registrations_homeroom, name='registrations_homeroom'),
    url(r'^registrations/homeroom/(?P<employee_number>\d+)/$', views.registrations_homeroom, name='registrations_homeroom'),
    url(r'^registrations/manage/$', views.registrations_manage, name='registrations_manage'),
    # url(r'^registrations/user/(?P<username>\w+)/$', views.registrations_user, name='registrations_user'),
    path('registrations/user/<str:username>/', views.registrations_user, name='registrations_user')
    # url(r'^registrations/homeroom/$', views.homeroom, name='homeroom'),

]

src/flex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from events import views as event_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

app_name = "flex"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', event_views.event_list, name='home'),
    # installed apps
    # url(r'^summernote/', include('django_summernote.urls')),
    # url(r'^accounts/', include('userena.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^select2/', include('django_select2.urls')),
    # custom apps
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^excuses/', include(('excuses.urls', 'excuses'), namespace='excuses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url

from . import views

app_name = "profiles"

urlpatterns = [
    # url(r'^$', views.ProfileList.as_view(), name='list'),
    # url(r'^import/$', views.mass_user_import, name='import'),
    url(r'^update/mass/$', views.mass_update, name='mass_update'),
    url(r'^(?P<id>\d+)/reset/$', views.reset_password_to_default, name='reset_password'),
    url(r'^permissions/update/$', views.permissions_update, name='permissions_update'),

]

src/events/models.py
import mimetypes
import urllib
from datetime import date, timedelta, datetime
from enum import Enum

import embed_video
import os

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.db import OperationalError, models
from django.urls import reverse
from django.db.models.signals import post_save
from django.utils import timezone

from embed_video.backends import detect_backend, UnknownBackendException

# Create your models here.
from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFill, SmartResize, ResizeToFit

from excuses.models import Excuse
from flex.utils import default_event_date


class CoreCompetency(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    link = models.URLField()
    icon = models.ImageField(null=True, blank=True, upload_to="icons/")

    class Meta:
        verbose_name_plural = "Core Competencies"

    def __str__(self):
        return self.name


class Category(models.Model):
    COLOR_CHOICES = (  # From bootstrap classes/highlighting
        (None, 'None'),
        ('warning', 'Yellow'),
        ('success', 'Green'),
        ('info', 'Blue'),
        ('danger', 'Red'),
    )
    DEFAULT_CATEGORY_ID = 1
    name = models.CharField(max_length=120)
    abbreviation = models.CharField(max_length=4)
    visible_in_event_list = models.BooleanField(default=False)
    sort_priority = models.IntegerField(default=0)
    color = models.CharField(max_length=10, choices=COLOR_CHOICES, default=None, blank=True, null=True,
                             help_text="Events will be highlighted with this color in the events list",)
    description = models.CharField(max_length=512, blank=True, null=True)

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['-sort_priority']

    def __str__(self):
        return self.name

    @classmethod
    def get_default(cls):
        try:
            if cls.objects.filter(name="Support").exists():
                return cls.objects.get(name="Support")
            else:
                return cls.objects.all().first()
        except OperationalError:
            pass  # tables don't exist, could happen when creating a new environment
            


class Location(models.Model):
    room_number = models.CharField(max_length=20, unique=True, help_text="e.g. B201")
    name = models.CharField(max_length=120, null=True, blank=True, help_text="e.g. Hackerspace (or) Couture's Room")

    def __str__(self):
        return self.room_number

    def get_name(self):
        if self.name:
            return self.name
        else:
            return ""

    def get_detailed_name(self):
        name_str = self.room_number
        if self.name:
            name_str += " (" + self.name + ")"
        return name_str

    def get_name_with_conflicts(self, date):
        events = self.event_set.filter(date=date)
        return self.get_detailed_name() + "" + str(events)

    class Meta:
        ordering = ['room_number']


class BlockManager(models.Manager):

    def get_flex_1(self):
        return self.active()[0]

    def get_flex_2(self):
        if not self.single_block():
            return self.active()[1]
        else:
            return None

    def single_block(self):
        """Check if the site is set up with only a single block, returns True or False
        """
        return self.active().count() == 1

    def get_only(self):
        return self.active().first()


    def active(self):
        return self.get_queryset().filter(active=True)

    def get_by_num(self, block_num):
        """ Gets the 1st or second active block """
        if int(block_num) == 1:
            return self.get_flex_1()
        elif not self.single_block() and int(block_num) == 2:
            return self.get_flex_2()
        else:
            return ValueError ("block_num was not 1 or 2.  Only two active blocks are currently supported")

    def get_num_from_id(self, id):
        """ Given a block object's ID, return 1 or 2 if it is the
        1st or second active block """
        if id == self.get_flex_1().id:
            return 1
        elif not self.single_block() and id == self.get_flex_2().id:
            return 2
        else:
            return ValueError ("That block is not active.")


class Block(models.Model):
    name = models.CharField(max_length=20)
    start_time = models.TimeField()
    end_time = models.TimeField()
    active = models.BooleanField(default=True)

    objects = BlockManager()

    class Meta:
        ordering = ['start_time']

    def __str__(self):
        return self.name

    def constant_string(self):
        """ Return either  FLEX1 or FLEX2 based on whether this is the first or second active flex block
        as there should only be one or two"""
        if self == Block.objects.get_flex_1():
            return "FLEX1"
        else:
            return "FLEX2"

    def synervoice_absent_string(self):
        return "F" + str(self.id) + "-ABS"

    def synervoice_noreg_string(self):
        return "F" + str(self.id) + "-NOREG"

    def synervoice_noreg_string(self):
        return "F" + str(self.id) + "-PRESENT_OR_EXCUSED"


class EventManager(models.Manager):
    def all_for_date(self, event_date, block=None):
        if block:
            qs = block.event_set.all()
        else:
            qs = self.get_queryset()
        return qs.filter(date=event_date)

    def all_visible_on_date(self, date):
        return self.get_queryset().filter(date=date, category__visible_in_event_list=True)

    def all_for_facilitator(self, user):
        return user.event_set.all()

    def all_active(self):
        """ Only events with at least one active block """
        return self.get_queryset().filter(blocks__in=Block.objects.active())


class Event(models.Model):

    F1_XOR_F2 = 0
    F1_OR_F2 = 1
    F1_AND_F2 = 2
    MULTI_BLOCK_CHOICES = (
        (F1_XOR_F2, 'Can choose one or the other, but not both.'),
        (F1_OR_F2, 'Can choose one block or both blocks.'),
        (F1_AND_F2, 'Both blocks are required.'),
    )

    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)  # MCE widget validation fails if required
    # description_image_file = models.ImageField(upload_to='images/', null=True, blank=True)
    description_image_file = ProcessedImageField(upload_to='images/', null=True, blank=True,
                                                 processors=[ResizeToFit(400, 400, upscale=False)],
                                                 format='JPEG',
                                                 options={'quality': 80},
                                                 help_text="Upload an image directly from your computer.  You can also "
                                                           "get an image from the web by pasting a direct link to the "
                                                           "image in the Description link field below.",
                                                 verbose_name="Image",
                                                 )
    description_link = models.URLField(
        "Description link (image, video, file, or webpage)",
        null=True, blank=True,
        help_text="An optional link to provide with the text description. Links to videos (YouTube or Vimeo) "
                  "or an image (must end in .png, .jpg, or .gif) will be embedded within the description."
                  "If the link is to another web page or a file, it will just display the link.")

    category = models.ForeignKey(Category, default=Category.DEFAULT_CATEGORY_ID, on_delete=models.SET_NULL, null=True,
                                 help_text="By default, events are sorted by category in the events list.")
    competencies = models.ManyToManyField(CoreCompetency, blank=True,
                                          help_text="The Core Competencies relevant to this event.")
    date = models.DateField(default=default_event_date)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    blocks = models.ManyToManyField(Block, help_text="In which block(s) will this event occur?")
    multi_block_event = models.IntegerField(
        default=F1_OR_F2,
        choices=MULTI_BLOCK_CHOICES,
        help_text="If the event is running in more than one block, what restrictions are there for students?  "
                  "This field is ignored if the event only occurs during one block.")
    facilitators = models.ManyToManyField(User, related_name='events',
                                          limit_choices_to={'is_staff': True})
    allow_facilitators_to_modify = models.BooleanField(
        default=True,
        help_text="If false, only the creator of the event can edit.  If true, then any staff member that is listed as "
                  "a facilitator will be able to edit the event.  The creator will always be able to edit this event, "
                  "even if they are not listed as one of the facilitators.")
    registration_cut_off = models.DurationField(
        default=timedelta(days=0, hours=0, minutes=5, seconds=0),
        help_text="How long before the start of the event does registration close?  After this time, "
                  "students will no longer be able to register for the event, nor will they be able to delete it "
                  "if they've already registered.")
    allow_registration_after_event_has_started = models.BooleanField(
        default=False,
        help_text="Students can continue to register for this event after it has already started, for the amount of "
                  "time indicated in the 'Registration cut off time'.  For example, if your cut off time is set to "

src/events/templates/events/date_filter.html
  <div style="width: 200px;">
    <form id="filter_form" method="GET" action="">
      <div class="input-group">
        <span class="input-group-addon" id="datepicker-label"><i class="fa fa-calendar"></i> Date</span>
        <input type="text"
                      id="datepicker"
                      name="date"
                      readonly="readonly"
                      class="form-control"
                      value="{{ date_filter }}"
        >
      </div>
    </form>
  </div>

src/events/templates/events/event_description.html
<div class="clearfix">
  {% if event.description_image_file %}
    <img src="{{ event.description_image_file.url }}"
         class="img-rounded img-responsive-50 pull-right hidden-sm"
         style="margin: 0 0 8px 8px;"
    >
  {% endif %}
  {{ event.description|safe|linebreaks }}

  {% if event.description_image_file %}
    <img src="{{ event.description_image_file.url }}"
            class="img-rounded img-responsive hidden-xs hidden-md hidden-lg">
  {% endif %}
  {% if event.video %}
    <!-- 16:9 aspect ratio -->
    <div class="embed-responsive embed-responsive-16by9 img-rounded hidden-print" style="margin: 0 0 8px 0;">
      <iframe class="embed-responsive-item" src="{{ event.video }}" allowfullscreen></iframe>
    </div>
    <div class="visible-print-block">
      <p>Video link: {{ event.video }}</p>
    </div>
  {% elif event.description_link and not event.image %}
    <p><a href="{{ event.description_link }}" target="_blank" ><i class="fa fa-link">&nbsp;&nbsp;</i>Link</a>
    <span class="visible-print-inline">: {{ event.description_link }}</span>
    </p>
  {% endif %}
</div>
{% if not no_buttons %}
{#  {% if request.user.is_superuser or request.user in event.get_editors %}#}
    {% if request.user.is_staff %}
    <div class="btn-group btn-group-sm pull-right hidden-print" role="group">
      <a title="Here you can Edit, Delete, or Duplicate to Future Weeks."
         class="btn btn-default wait" href="{% url 'events:update' event.id %}">
        <i class="fa fa-edit"></i> Edit
      </a>
      <a title="Create a single copy of this event where you can edit the copy before saving it.  To duplicate an event multiple times for future weeks, use the Edit button and set the 'Duplicate to future weeks' field at the bottom of the form."
          class="btn btn-default wait" href="{% url 'events:copy' event.id %}">
        <i class="fa fa-copy"></i> Copy
      </a>
      <a title="Numbers indicate how many students have registered for this event in each block it is available.  Red indicates the event is full."
         class="btn btn-primary wait" href="{% url 'events:attendance' event.id %}">
        <i class="fa fa-users"></i> Attendance
        {% for num in event.get_attendances %}
          <span class="badge {% if event.max_capacity == num %}badge-attendance-full{% endif %}">{{ num }}</span>
        {% endfor %}
      </a>
    </div>
  {% endif %}
{% endif %}

src/events/templates/events/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block style %}
    <!-- form.media -->
    {{ form.media.css }}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/duration-picker.css' %}">
    <link rel="stylesheet" href="{% static 'css/events.css' %}">
    <style>
        /* A form element generated by django that we want hidden by default */
        #div_id_multi_block_event {
            display: none;
        }
    </style>
{% endblock style %}

{% block content %}
    <div class="row">
        <div class="col-sm-10 col-md-8 col-lg-6">

            <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
                <h1 class="clearfix">{{ title }}
                    <div class="btn-group pull-right" role="group">

                        <a class="btn btn-default" href="{% url 'events:list' %}">Cancel</a>
                        <input class="btn btn-primary" type="submit" value="{{ btn_value }}"/>
                        {% if delete_btn %}
                            <a class="btn btn-danger" href="{% url 'events:delete' event.id %}">Delete</a>{% endif %}

                    </div>
                </h1>
                {{ form|crispy }}
                <div class="btn-group pull-right" role="group">

                    <a class="btn btn-default" href="{% url 'events:list' %}">Cancel</a>
                    <input class="btn btn-primary" type="submit" value="{{ btn_value }}"/>
                    {% if delete_btn %}
                        <a class="btn btn-danger" href="{% url 'events:delete' event.id %}">Delete</a>{% endif %}

                </div>
            </form>


        </div>

    </div>
    <br/>


{% endblock content %}

{% block js %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/duration-picker.js' %}"></script>
    {{ form.media.js }}

    <script>

        var $date =  $("#id_date");
        let $location = $("#id_location");
        // container for tick boxes and labels for flex-1 and flex-2
        var $blocks = $('#div_id_blocks>div.controls label');

        function validateLocation() {
            var blocks = getSelectedBlocks();
            console.log(blocks);
            $.ajax({
                url: '{% url "events:validate_location" %}',
                data: {
                    'location_id': $location.val(),
                    'date': $date.val(),
                    'blocks[]': JSON.stringify(blocks),
                    'event_id': {{ event.id|default:"null" }}
                },
                dataType: 'json',
                success: function (data) {
                    if (data.conflict) {
                        alert(data.msg);
                    }
                }
            });
        }

        // display the multi block event field if more than one block is ticked.
        function updateMultiBlockEventField($blocks) {
            var $multiblock = $('#div_id_multi_block_event');
            var $blocksTicked = $blocks.find('input:checked');
            if ($blocksTicked.length > 1) {
                $multiblock.slideDown();
            }
            else {
                $multiblock.slideUp();
            }

            validateLocation();
        }

        function getSelectedBlocks() {
            var blocks_selected = [];
            $blocks.find('input:checked').each(function() {
                blocks_selected.push($(this).attr('value'));
            });
            return blocks_selected;
        }

        function updateCategorySpecificField($category) {
            var selection = $category.find("option:selected").text();
            var $fieldsToToggle = $('#div_id_multi_block_event',
                '#div_id_description',
                '#div_id_description_link',
                '#div_id_registration_cut_off',
                '#div_id_duplicate');


            if (selection == "Prep" || selection == "Collaboration") {
                $fieldsToToggle.slideUp();
            }
            else {
                $fieldsToToggle.slideDown();
            }

        }

        $(document).ready(function () {

            // Add listeners to check for location conflicts
            $location.change(validateLocation);
            // $date.change(validateLocation); // needs to be done in events-datepicker-v3.js
            // $blocks.change(...); this is done in updateMultiBlockEventField()

            /***************************************
             *
             * CONDITIONAL DISPLAY OF MULTI-BLOCK EVENTS FIELD
             *
             * *************************************/

            // update when page loads in case already more than one block ticked (possible if editing an existing event)
            updateMultiBlockEventField($blocks)

            /***************************************
             *
             *  CONDITIONAL DISPLAY FOR PREP OR COLLAB
             *
             *************************************/
            var $category = $('#div_id_category>div.controls select');
            updateCategorySpecificField($category);

            /***************************************
             *
             * PREVENT CHANGES TO SOME FIELDS IF ALREADY HAS REGISTRANTS
             *
             * *************************************/

                {% if has_registrants %}
                    var disabled_elms = [];

                    disabled_elms.push($date)
                    $date.after("<p class='help-block'>You can't change the date of an event that already has students " +
                        "registered for it.  If there is a problem with this event, you can delete it; " +
                        "This will boot out any registered students.  If you want to make a copy of this event for a " +
                        "future date, go back and hit the copy button.</p>");

                    var $blocks_input = $("input[name='blocks']");
                    disabled_elms.push($blocks_input);
                    $("#hint_id_blocks")
                        .html("<p class='help-block'>You can't change available blocks of an event that already has " +
                            "students registered for it.  If there is a problem with this event, you can delete it; " +
                            "This will boot out any registered students.</p>");

                    var $multi_block = $("#id_multi_block_event");
                    disabled_elms.push($multi_block)
                    $("#hint_id_multi_block_event")
                        .html("<p class='help-block'>You can't change the block options of an event that already has " +
                            "students registered for it.  If there is a problem with this event, you can delete it; " +
                            "This will boot out any registered students.</p>");

                    // create a copy of the disabled fields, enable them, and hide them
                    // these are needed so the data will get sent with the form.  Otherwise required fields will be blank
                    disabled_elms.forEach(function ($elm) {
                        $elm.prop('disabled', true);
                        var $clone = $elm.clone()
                        $clone.prop('disabled', false);
                        $clone.hide();
                        $elm.after($clone);
                    });

                {% else %}
                    $blocks.click(function () { // when changing number of blocks, display multiEvent field as appropriate
                        updateMultiBlockEventField($blocks);
                    });
                    $category.change(function () {
                        updateCategorySpecificField($category);
                    });


                {% endif %}

            /***************************************
             *
             * DURATION PICKER STUFF
             *
             * *************************************/
            var $cut_off_input = $('#id_registration_cut_off');


            // get value before widget takes over, use it to set the widgets value after widget is created (see below)
            var raw_value = $cut_off_input.val();

            var durationPicker = $cut_off_input.durationPicker({
                days: {
                    label: 'days',
                    min: 0,
                    max: 30,
                    seperator: " ",
                },
                hours: {
                    label: 'hrs',
                    min: 0,
                    max: 24,
                    seperator: ":",
                },
                minutes: {
                    label: 'min',
                    min: 0,
                    max: 60,
                    seperator: ":00",
                },
            });

            var split_values = raw_value.split(" "); // check if there is a day in  dd hh:mm:ss
            // if days found, it will be in first element split by a space: "[dd] hh:mm:ss"
            var days = split_values.length > 1 ? split_values[0] : 0;
            // pop the last value in the array (might be one or two elements, depending if days present)
            // then split again for hh:mm:ss
            split_values = split_values.pop().split(":"); // get last value of array, if more than one.
            var values = {days: days, hours: split_values[0], minutes: split_values[1]};
            durationPicker.setvalues(values);

            // Bootstrap styling to form-control
            $('.durationpicker-container.form-control')
                .focusin(function () {
                    $(this).addClass('focus');
                })
                .focusout(function () {
                    $(this).removeClass('focus');
                });


            // tooltips
            $('.has-popover').popover({'trigger': 'hover'});

            /***************************************
             *
             * ADD COMPETENCY DESCRIPTIONS
             *
             * *************************************/


        }); // $(document).ready()
    </script>

    <script id="event-datepicker" data-date-input-id="id_date" src="{% static 'js/events-datepicker-v3.js' %}"></script>

{% endblock js %}

src/events/templates/events/homeroom_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
{#  <link rel="stylesheet" href="{% static 'chosen_v1.6.2/chosen.css' %}">#}
  <link rel="stylesheet" href="{% static 'css/events.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock style %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}



{% block content %}

  <p class="pull-right text-muted">
    <br>Total registrations:
    {% for key, value in counts_dict.items %}
        {{value}} ({{key}}),
    {% endfor %}
  </p>

  <h1>{{ heading }}</h1>

    <div id="toolbar">
        {%  include 'events/date_filter.html' %}
    </div>
    <table data-toolbar="#toolbar"
           data-toggle="table"
           data-classes="table table-hover table-no-bordered table-condensed"
         data-search="true"
         data-id-field="id"
         data-sort-name="last"
         data-sort-order="asc"
         id="table">
    <thead>
    <tr>
      <th data-field="id" data-sortable="true">Number</th>
      <th data-field="first" data-sortable="true">First Name</th>
      <th data-field="last" data-sortable="true">Last Name</th>
      <th data-field="grade" data-sortable="true">Grade</th>
      <th data-field="homeroom"
          data-sortable="true"
          data-visible="{{ include_homeroom_teacher }}"
      >
          Homeroom</th>
      <th data-field="absent" data-sortable="true">Flex 1</th>
      <th data-field="late" data-sortable="true">Flex 2</th>
      <th data-field="permission" data-sortable="true"
      title="Yearlong permission granted for low risk excursions.">Permission</th>
      <th {% if include_homeroom_teacher and not request.user.is_superuser %}data-visible="false"{% endif %}>Reset PW</th>
    </tr>
    </thead>
    <tbody>
    {% for student in students %}
      <tr>
        <td><a href="{% url 'events:registrations_user' student.username  %}">{{ student.username }}</a></td>
        <td>{{ student.first_name }}</td>
        <td>{{ student.last_name }}</td>
        <td>{{ student.profile__grade }}</td>
        <td>{{ student.profile__homeroom_teacher}}</td>
        <td>
          {% if student.FLEX1 %}<a href="{{ student.FLEX1_url }}attendance/">{{ student.FLEX1 }}</a>
          {% elif student.FLEX1_excuse %}Excused ({{ student.FLEX1_excuse }})
          {% else %}-{% endif %}
        </td>
        <td>
          {% if student.FLEX2 %}<a href="{{ student.FLEX2_url }}attendance/">{{ student.FLEX2 }}</a>
          {% elif student.FLEX2_excuse %}Excused ({{ student.FLEX2_excuse }})
          {% else %}-{% endif %}
        </td>
       <td>{{ student.profile__permission|yesno:"Yes,No,Incomplete" }}</td>
        <td>
          <a class="reset-password"
             data-user="{{ student.username }}"
             href="{% url 'profiles:reset_password' student.id %}"
             title='Reset password to "wolf"'>
            <i class="fa fa-key"></i>
          </a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock content %}

{% block js %}
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  {#  Date Filter#}
  <script src="{% static 'js/events-datepicker-v3.js' %}"></script>

  <!-- Bootstrap Tables:  http://bootstrap-table.wenzhixin.net.cn/ -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>

{#  Confirm password reset#}
  <script>
    $(document).ready(function() {
      $('.reset-password').click(function() {
        console.log(this);
        if (confirm('Reset password to "wolf" for user ' + $(this).data('user') + "?")) {
          var url = $(this).attr('href');
          $('#content').load(url);
        }
        else
            return false
      });
    });
  </script>
{% endblock js %}